backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ssZ"
        date_format: "YYYY-MM-DD"
        time_format: false
      - label: "Author"
        name: "author"
        widget: "string"
        default: "NutriGLP Team"
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: false
      - label: "Body"
        name: "body"
        widget: "markdown"
